### ISSUE TITLE
init.d service not working

### ISSUE THREAD

**Issue by juranich** [rmoesbergen/openwrt#2]
For some reason, the init.d service was not launching the python script.
I've modified the service script slightly and it works for me. Just sharing with anyone who experiences this issue.
`  GNU nano 5.2             /etc/init.d/presence-detector                        
#!/bin/sh /etc/rc.common

START=90
STOP=1
USE_PROCD=1
NAME=devices
PROG=/etc/config/presence-detector.py

start_service() {
        echo "Starting Detector Service..."
        procd_open_instance
        procd_set_param command /usr/bin/python3 "$PROG"
        procd_close_instance
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_set_param respawn
}
`

**Comment by hugalafutro** [comment]
Hi,
I had the same issue, your init script works, but I was wondering where do I go from there, how do I integrate it into HA, like where does the sensor show ?

**Comment by rmoesbergen** [comment]
Hi, thanks for reporting this. I personally don't see this issue but updated the initscript anyway since it looks more complete.

@hugalafutro The script sends mac address presence events to home assistant, so all your wifi devices should appear in home assistant as device_tracker.<mac address> entities with an updated 'home' or 'away' status. See Configuration -> Entities in the UI. Also make sure you have device_tracker enabled in your configuration.yaml. For more info, see: 
https://www.home-assistant.io/integrations/device_tracker/
