### ISSUE TITLE
device attached to second AP not seen

### ISSUE THREAD

**Issue by ccheath** [rmoesbergen/openwrt#53]
I've got a DLink ex3700 range extender in my OpenWRT setup and devices that attach to it are not seen by the presence detector... is there a way around this? I don't think I can install/run this on the ex3700 (and that seems like it would be redundant).

**Comment by rmoesbergen** [comment]
Hi @ccheath , it looks like your range extender is actually acting as a separate access point. So devices connect to its wifi network instead of that of your router. This means mac address/association is never seen by your router and presence-detector doesn't see it either. There's not much it can do about that. The only way I see around this would be to change the "mode" of the extender to be an actual ("dumb") extender instead of an additional access point.

**Comment by ccheath** [comment]
@rmoesbergen do you have any advice/links to where i can change the 'mode'? (tyia)

**Comment by rmoesbergen** [comment]
https://www.downloads.netgear.com/files/GDC/EX3700/EX3700_UM_EN.pdf

Using the 'range extender' mode, not 'access point' mode might work.

**Comment by ccheath** [comment]
@rmoesbergen I've already flashed OpenWRT onto the ex3700... can I still do it?

**Comment by rmoesbergen** [comment]
Oh, in that case you can just install presence detector on it.

**Comment by ccheath** [comment]
@rmoesbergen .... no can do... there's literally no space on the ex3700 to install python (only like 1MB available)

got any other ideas?

**Comment by rmoesbergen** [comment]
> @rmoesbergen .... no can do... there's literally no space on the ex3700 to install python (only like 1MB available)
> 
> got any other ideas?

Maybe this works? https://openwrt.org/docs/guide-user/additional-software/imagebuilder

**Comment by ccheath** [comment]
@rmoesbergen - thanks for the suggestion... I ended up using the iPhone Device Tracker from HACS.
